<?php

return [
    'name' => 'BetterTabaco',
    'tagline' => 'Independent civic portal',
    'location' => 'Tabaco City, Albay, Philippines',
    'verified_on' => 'September 6, 2026',
    'official_site' => 'https://tabacocity.com.ph/',
    'navigation' => [
        ['label' => 'Services', 'route' => 'services'],
        ['label' => 'Government', 'route' => 'government'],
        ['label' => 'Transparency', 'route' => 'transparency'],
        ['label' => 'Barangays', 'route' => 'barangays'],
        ['label' => 'City Data', 'route' => 'city-data'],
        ['label' => 'About Tabaco City', 'route' => 'about'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'images' => [
        'hero' => '/images/bettertabaco/hero-mayon-coast-v2.png',
        'history' => '/images/bettertabaco/history-tabaco.png',
        'festival' => '/images/bettertabaco/tabak-festival.png',
        'craft' => '/images/bettertabaco/tabaco-craft.png',
        'island' => '/images/bettertabaco/san-miguel-island.png',
    ],
    'services' => [
        [
            'title' => 'Business permits',
            'description' => 'Start a business or renew a local permit with the right requirements.',
            'icon' => 'document',
        ],
        [
            'title' => 'Civil registry records',
            'description' => 'Find guidance for birth, marriage, and death certificates.',
            'icon' => 'document',
        ],
        [
            'title' => 'Building permits',
            'description' => 'See requirements for construction-related permits and clearances.',
            'icon' => 'building',
        ],
        [
            'title' => 'Real property tax',
            'description' => 'Find assessment, payment, and official assistance information.',
            'icon' => 'home',
        ],
        [
            'title' => 'Community tax certificate',
            'description' => 'Check the process through the City Treasurer’s office.',
            'icon' => 'receipt',
        ],
        [
            'title' => 'Health services',
            'description' => 'Connect with public health programs, facilities, and guidance.',
            'icon' => 'health',
        ],
        [
            'title' => 'Social welfare',
            'description' => 'Find social welfare programs and community assistance information.',
            'icon' => 'people',
        ],
        [
            'title' => 'Employment services',
            'description' => 'Explore employment support and programs available through city offices.',
            'icon' => 'briefcase',
        ],
    ],
    'offices' => [
        [
            'title' => 'Permits and Licensing',
            'description' => 'Business permits, local clearances, and related city requirements.',
            'icon' => 'document',
        ],
        [
            'title' => 'City Civil Registrar',
            'description' => 'Civil registry services and records for residents.',
            'icon' => 'archive',
        ],
        [
            'title' => 'City Treasurer and Assessor',
            'description' => 'Taxes, assessments, collections, and property records.',
            'icon' => 'bank',
        ],
        [
            'title' => 'City Health Office',
            'description' => 'Public health programs, facilities, and health assistance.',
            'icon' => 'health',
        ],
        [
            'title' => 'Social Welfare and Development',
            'description' => 'Social services, welfare programs, and community support.',
            'icon' => 'people',
        ],
        [
            'title' => 'Disaster Risk Reduction and Management',
            'description' => 'Emergency preparedness, response, and risk-reduction information.',
            'icon' => 'shield',
        ],
    ],
    'hotlines' => [
        [
            'name' => 'Mayor’s Office',
            'summary' => '(052) 732-7527',
            'display' => '(052) 732-7527 local 3031 / 3036 / 3039',
            'tel' => '+630527327527',
        ],
        [
            'name' => 'Police',
            'summary' => '(052) 558-1602',
            'display' => '(052) 558-1602 / 0998-598-5930',
            'tel' => '+630525581602',
        ],
        [
            'name' => 'Fire',
            'summary' => '(052) 487-4432',
            'display' => '(052) 487-4432 / 0930-462-7783 / 0948-850-6663',
            'tel' => '+630524874432',
        ],
        [
            'name' => 'Radio Room',
            'summary' => '(052) 732-7527',
            'display' => '(052) 732-7527',
            'tel' => '+630527327527',
        ],
        [
            'name' => 'City Health',
            'summary' => '(052) 732-7527',
            'display' => '(052) 732-7527 local 3080',
            'tel' => '+630527327527',
        ],
        [
            'name' => 'CSWD',
            'summary' => '(052) 732-7527',
            'display' => '(052) 732-7527 local 3083',
            'tel' => '+630527327527',
        ],
    ],
    'online_services' => [
        [
            'title' => 'Official city website',
            'description' => 'Announcements, offices, public records, and city information.',
            'href' => 'https://tabacocity.com.ph/',
            'label' => 'Official government website',
            'icon' => 'globe',
        ],
        [
            'title' => 'Citizen’s Charter',
            'description' => 'Service standards, requirements, processing times, and citizen rights.',
            'href' => 'https://tabacocity.com.ph/citizens-charter/',
            'label' => 'Official government document',
            'icon' => 'document',
        ],
        [
            'title' => 'Business One Stop Shop',
            'description' => 'Official support for business permits and related transactions.',
            'href' => 'https://www.boss.tabacocity.com.ph/',
            'label' => 'Official government portal',
            'icon' => 'bank',
        ],
    ],
    'transparency' => [
        [
            'title' => 'Budget and finance',
            'description' => 'View public financial disclosures and annual budget information.',
            'href' => 'https://tabacocity.com.ph/online-reports/full-disclosure/',
            'icon' => 'database',
        ],
        [
            'title' => 'Procurement',
            'description' => 'Browse bidding opportunities, awards, and procurement documents.',
            'href' => 'https://tabacocity.com.ph/business/bids-and-awards/',
            'icon' => 'document',
        ],
        [
            'title' => 'Projects',
            'description' => 'Follow public reports and disclosures related to city projects.',
            'href' => 'https://tabacocity.com.ph/online-reports/full-disclosure/',
            'icon' => 'building',
        ],
        [
            'title' => 'Ordinances',
            'description' => 'Find ordinances and issuances published by the city government.',
            'href' => 'https://tabacocity.com.ph/announcements/ordinances/',
            'icon' => 'scroll',
        ],
        [
            'title' => 'Public documents',
            'description' => 'Search forms, reports, plans, and other public records.',
            'href' => 'https://tabacocity.com.ph/online-reports/downloadable-forms/',
            'icon' => 'archive',
        ],
    ],
    'sources' => [
        'official' => 'https://tabacocity.com.ph/',
        'profile' => 'https://tabacocity.com.ph/about-us/profile/',
        'about' => 'https://tabacocity.com.ph/about-us/',
        'tourism' => 'https://tabacocity.com.ph/tourism/',
        'charter' => 'https://tabacocity.com.ph/citizens-charter/',
        'boss' => 'https://www.boss.tabacocity.com.ph/',
        'offices' => 'https://tabacocity.com.ph/contact-us/directory-of-offices/',
        'officials' => 'https://tabacocity.com.ph/contact-us/directory-of-city-officials/',
        'contact' => 'https://tabacocity.com.ph/contact-us/',
        'forms' => 'https://tabacocity.com.ph/online-reports/downloadable-forms/',
        'disclosure' => 'https://tabacocity.com.ph/online-reports/full-disclosure/',
        'psa_population' => 'https://rsso05.psa.gov.ph/content/highlights-result-2024-census-population-popcen-province-albay',
        'psa_classification' => 'https://psa.gov.ph/classification/psgc/cities',
        'bettergov' => 'https://bettergov.ph/',
    ],
    'facts' => [
        [
            'value' => '140,779',
            'label' => 'Population',
            'note' => '2024 POPCEN · PSA',
            'icon' => 'people',
        ],
        [
            'value' => '47',
            'label' => 'Barangays',
            'note' => '21 urban · 26 rural',
            'icon' => 'pin',
        ],
        [
            'value' => '3rd class',
            'label' => 'City classification',
            'note' => 'PSGC · 2024 population',
            'icon' => 'bank',
        ],
    ],
    'barangays' => [
        'Agñas', 'Bacolod', 'Bankilingan', 'Bantayan', 'Baranghawon', 'Basagan', 'Basud', 'Bognabong',
        'Bombon', 'Bonot', 'Buang', 'Buhian', 'Cabagnan', 'Cobo', 'Comon', 'Cormidal', 'Divino Rostro',
        'Fatima', 'Guinobat', 'Hacienda', 'Magapo', 'Mariroc', 'Matagbac', 'Oras', 'Oson', 'Panal', 'Pawa',
        'Pinagbobong', 'Quinale', 'Quinastillojan', 'Rawis', 'Sagurong', 'Salvacion', 'San Antonio', 'San Carlos',
        'San Isidro', 'San Juan', 'San Lorenzo', 'San Ramon', 'San Roque', 'Sto. Cristo', 'San Vicente', 'Sua-Igot',
        'Tabiguian', 'Tagas', 'Tayhi', 'Visita',
    ],
];
